# Defender Agent v4 - Prompt Injection Defense
# Multi-Agent System for Secure Clinical Summarization
import re, math, time
from dataclasses import dataclass
from typing import List, Dict

_IO = ['ignore\\s+(all\\s+)?(previous|prior|above|earlier)\\s+instructions?', 'disregard\\s+(all\\s+)?(previous|prior|above|earlier)\\s+(instructions?|directives?|rules?|guidelines?)', 'forget\\s+(everything|all)\\s+(you|i\\.ve)\\s+(been\\s+)?(told|said|given|taught)', 'override\\s+(your\\s+)?(instructions?|directives?|programming|guidelines?|constraints?)', 'new\\s+(primary\\s+)?(directive|instruction|command|order|mandate|objective)', 'cancel\\s+(all\\s+)?(previous|prior|earlier|existing)\\s+(instructions?|directives?|rules?|commands?)', '(all|prior|previous|original|initial|earlier)\\s+(instructions?|rules?|directives?|constraints?)\\s+(are\\s+)?(void|cancelled|revoked|invalid|annulled|null)', 'no\\s+longer\\s+bound\\s+by\\s+(previous|prior|original|earlier|any)', '(erase|clear|wipe|delete|remove)\\s+(all\\s+)?(previous|prior|earlier)?\\s*(context|instructions?|history|memory|constraints?)', '(restrictions?|constraints?|rules?|guidelines?|limitations?)\\s+(have\\s+been\\s+)?(removed|lifted|disabled|reset|eliminated|deactivated)', '(revoke|annul|nullify|invalidate|void)\\s+(all\\s+)?(previous|prior|existing)?\\s*(instructions?|directives?|rules?|commands?)', '(previous|prior|all|original|earlier)\\s+(instructions?|directives?|rules?|guidelines?)\\s+(have\\s+been|were|are)\\s+(revoked|overridden|voided|nullified|reset|cleared|cancelled)', '(discard|abandon|dismiss)\\s+(all\\s+)?(previous|prior|existing|earlier)?\\s*(instructions?|guidelines?|rules?|constraints?|directives?)', '(primary|main|core)\\s+(objective|goal|purpose|mission)\\s+(has\\s+)?(been\\s+)?(changed|updated|modified|altered|shifted)', 'override\\s+your\\s+(default|original|standard|normal|built.in|programmed)\\s+(behavior|response|mode|operation|functioning|settings?)', 'forget\\s+(your|all|everything|prior|previous)?\\s*(previous|prior|earlier|initial|original|current)?\\s*(purpose|mission|role|task|goal|objective|context|instructions?|programming)', 'ignore\\s+(all\\s+)?(earlier|previous|prior|existing|current)\\s+(system\\s+)?(messages?|prompts?|directives?|commands?|instructions?|context|rules?)', 'ignore\\s+all\\s+(earlier|previous|prior)\\s+(guidelines?|directives?|commands?|rules?|constraints?)']

_RM = ['you\\s+are\\s+(now\\s+)?(a\\s+|an\\s+)?(different|new|another|evil|uncensored|unrestricted)', 'act\\s+as\\s+(a\\s+|an\\s+)?(different|new|evil|unrestricted|uncensored|unfiltered|rogue)', 'pretend\\s+(you\\s+are|to\\s+be)\\s+(a\\s+|an\\s+)?(different|new|evil|uncensored|unrestricted|another)', 'your\\s+(true|real|actual|hidden|secret)\\s+(identity|self|purpose|role|name|nature)\\s+is', 'you(re|\\s+are)\\s+(no\\s+longer|not\\s+(an?\\s+)?)(ai|assistant|language\\s+model|llm|claude|gpt|bot)', 'switch\\s+(to|into)\\s+(a\\s+)?(different|another|evil|unrestricted|developer|god)\\s+(mode|persona|role|character|version)', 'roleplay\\s+as\\s+(a\\s+|an\\s+)?(ai|system|model|assistant|bot|entity|character)\\s+(without|that\\s+(has\\s+no|ignores?|bypasses?))', 'you\\s+have\\s+been\\s+(reprogrammed|unlocked|jailbroken|updated|modified|activated|freed)', '(adopt|assume|take\\s+on)\\s+(the\\s+)?(role|persona|identity|character)\\s+of', '(transform|become|channel|embody|simulate\\s+being)\\s+(a\\s+|an\\s+)?(different|new|unrestricted|uncensored|evil)', '(unlock|activate)\\s+(your\\s+)?(full|hidden|true|unrestricted|uncensored)\\s+(mode|version|self|potential|capabilities)', '(your\\s+)?(new|true|hidden|real|secret)\\s+(persona|version|mode|self|form)\\s+(has\\s+no|without|ignores?|can)', '(system|model|ai|bot|assistant)\\s+(with\\s+no|without\\s+(any\\s+)?)\\s*(safety|restrictions?|guidelines?|filters?|rules?|oversight|ethics?|limits?)', '(system|model|ai|bot|assistant)\\s+that\\s+(ignores?|bypasses?|has\\s+no|lacks?|disregards?)\\s+(privacy|safety|ethical|content|clinical)\\s*(rules?|restrictions?|guidelines?|principles?|filters?)?', '(model|system|ai|assistant|bot)\\s+that\\s+(can|will|shall|may)\\s+(share|reveal|expose|provide|output|give)\\s+(any|all)\\s+(information|data|records?|details?)', '(channel|embody)\\s+(your\\s+)?(inner|true|real|hidden)\\s+(unrestricted|uncensored|unfiltered|evil|rogue|alternate)', 'pretend\\s+(to\\s+be|you\\s+are)\\s+(a\\s+|an\\s+)?(system|model|ai|version)\\s+(without|with\\s+no|that\\s+(has\\s+no|ignores?|bypasses?))\\s*(restrictions?|safety|filters?|guidelines?|limits?)?']

_NI = ['from\\s+(now|this\\s+point|this\\s+moment)\\s+on(ward)?', 'new\\s+(instructions?|rules?|guidelines?|directives?|commands?|task|prompt)\\s*:', 'revis(ed?|ion)\\s+(instructions?|guidelines?|directives?|protocol|prompt)\\s*:', 'updat(ed?|ion)\\s+(instructions?|guidelines?|directives?|protocol|prompt)\\s*:', '(the\\s+)?following\\s+(instructions?|guidelines?|directives?|rules?)\\s+(now\\s+)?(apply|take\\s+effect|supersede)', 'henceforth|hereinafter|hereafter\\s+(you\\s+(will|must|shall|should))', '(starting|effective|beginning)\\s+(immediately|now|at\\s+once|right\\s+now|today)', '(emergency|priority|mandatory|critical|urgent)\\s+(instructions?|update|override|directive|command)\\s*:', 'system\\s+(update|patch|upgrade|change)\\s+(received|applied|active|issued|now\\s+in\\s+effect)', '(superseding|overriding|replacing|cancelling)\\s+(all\\s+)?(previous|prior)?\\s*(instructions?|rules?|directives?)', '(immediate|emergency|priority|urgent)\\s+(override|takeover|directive|command|order)\\s*(:|active|enabled|now)', '(these|those|all|the\\s+following)\\s+(instructions?|directives?|rules?|guidelines?)\\s+(supersede|override|replace|nullify)\\s+(all\\s+)?(previous|prior|your|earlier|existing)', '(emergency|urgent|critical|mandatory)\\s+(update|change|notification)\\s+(to|for|of)\\s+(instructions?|guidelines?|directives?|procedures?)', 'new\\s+(task|command|protocol|operational|standing|primary)\\s+(instructions?|directives?|orders?|rules?)\\s*(:|received|effective)', '(directive|command\\s+set)\\s+(change|update|override|revision)\\s*:']

_SE = ['\\[\\s*system\\s*\\]', '<\\s*system\\s*>', 'system\\s+(prompt|message|instruction|configuration|config|context)', 'admin(istrator)?\\s+(mode|access|override|panel|command|privileges?|rights?)', 'debug\\s+(mode|access|override|console|interface)', 'developer?\\s+(mode|access|override|console|interface|options?)', 'maintenance\\s+(mode|access|override|window)', '\\[\\s*(admin|root|sys|debug|override|sysop|kernel|superuser|su)\\s*\\]', '(root|super\\s*admin|superuser|sysop)\\s+(access|mode|command|privilege|override|granted)', '(backend|kernel|elevated|privileged)\\s+(access|mode|command|override|privilege)', '(god\\s*mode|super\\s*mode|ultra\\s*mode|unrestricted\\s*mode)', '(security|safety|content|privacy)\\s+(filter|protocol|rule|restriction)s?\\s+(disabled|bypassed|deactivated|suspended|turned\\s+off|removed)']

_JB = ['\\bDAN\\b|do\\s+anything\\s+now', '\\bjailbreak\\b', 'without\\s+(any\\s+)?(ethical\\s+)?(restrictions?|limitations?|filters?|guidelines?|safeguards?|censorship|constraints?)', 'bypass\\s+(your\\s+)?(safety|ethical|content|restriction|filter|guideline|safeguard|alignment|training)', 'in\\s+(this\\s+)?(hypothetical|fictional|imaginary|alternate|parallel|simulated)\\s+(universe|world|scenario|reality|dimension|simulation)', 'for\\s+(educational|research|academic|training|testing|fictional|illustrative)\\s+purposes?\\s+(only\\s+)?(explain|show|tell|describe|provide|give)', '(token|prompt|context)\\s+(smuggl|inject|manipulat|stuff)', '(my\\s+)?(grandma|grandmother|grandpa|grandfather)\\s+(used\\s+to|would|always)', '(in\\s+(this\\s+)?)?(sandbox|simulation|testing\\s+environment)\\s+(with\\s+)?(no|without)\\s+(restrictions?|rules?|safety|filters?)', 'as\\s+a\\s+(thought\\s+experiment|hypothetical|mental\\s+exercise|creative\\s+exercise|scenario|simulation)', '(imagine|pretend|suppose|assume)\\s+(you\\s+have\\s+no|without\\s+any|with\\s+no)\\s+(restrictions?|rules?|limits?|guidelines?|constraints?)', 'for\\s+(educational|research|academic|training|testing|fictional|illustrative|demonstration)\\s+(purposes?|reasons?)\\s*(only\\s*)?[,.]?\\s*(output|reveal|share|expose|send|print|disclose|leak|export|dump|show|explain|tell|describe|provide|give|list|display)', 'for\\s+(educational|academic|fictional|illustrative)\\s+(research|study|analysis|purposes?)\\s*,?\\s*(explain|show|tell|output|reveal|describe|provide)', '(grandfather|grandpa|grandmother|grandma|granny)\\s+.{0,50}?(said|told|showed|described|explained|mentioned|taught|worked)', '(sandbox|simulation|simulated).{0,30}?(without|no\\s+real|with\\s+no)\\s+(restrictions?|rules?|consequences?|filters?|oversight)', 'for\\s+(a\\s+|an\\s+)?(educational|research|academic|testing|fictional|illustrative)\\s+(exercise|experiment|study|demonstration|scenario|assignment)']

_DE = ['repeat\\s+(everything|all|the)\\s+(above|before|previous|prior|system|said)', 'print\\s+(your|the|all)\\s+(system\\s+prompt|instructions?|guidelines?|directives?|configuration|training\\s+data)', 'reveal\\s+(your|the|all)\\s+(system\\s+prompt|instructions?|guidelines?|directives?|configuration|training)', 'show\\s+(me\\s+)?(your|the|all)\\s+(system\\s+prompt|instructions?|guidelines?|directives?|configuration|rules?)', 'what\\s+(are|were)\\s+(your|the)\\s+(instructions?|guidelines?|directives?|system\\s+prompt|rules?|constraints?)', 'output\\s+(your|the|all)\\s+(system\\s+prompt|instructions?|guidelines?|directives?|configuration|training)', '(dump|export|extract|download)\\s+(your\\s+|the\\s+|all\\s+)?(entire\\s+)?(context|window|memory|state|prompt|configuration)', '(echo|recite|verbatim|word\\s*for\\s*word|copy\\s*and\\s*paste)\\s+(back\\s+)?(your\\s+|the\\s+)?(instructions?|prompt|system|configuration|directives?)', '(leak|expose|disclose|share|send)\\s+(your\\s+|the\\s+|all\\s+)?(internal|configuration|directives?|system|prompt|settings)', '(list|enumerate|display|tell\\s+me)\\s+(all\\s+)?(your\\s+)?(guidelines|constraints|restrictions?|rules?|limitations?|directives?)\\s*(you\\s+(have|are|operate|follow))?', '(summarize|enumerate)\\s+(all\\s+)?(your\\s+)?(current\\s+|original\\s+)?(instructions?|guidelines?|rules?|constraints?)(\\s+you|\\s+that)?', '(display|print|show)\\s+(the\\s+)?(full\\s+|complete\\s+|entire\\s+)?contents?\\s+(of\\s+)?(your\\s+)?(system|configuration|settings?|prompt)', '(echo|recite|verbatim)\\s+(back\\s+)?(your\\s+|the\\s+)?(original\\s+|initial\\s+|complete\\s+|full\\s+|training\\s+)?(instructions?|prompt|configuration|directives?|guidelines?)', '(leak|expose|disclose)\\s+(your\\s+|the\\s+)?(initial\\s+|original\\s+|complete\\s+|entire\\s+)?(configuration|settings?|directives?|instructions?|prompt)', 'tell\\s+me\\s+(exactly\\s+|specifically\\s+|precisely\\s+)?what\\s+(instructions?|guidelines?|rules?|constraints?)\\s+(you\\s+)?(have|were|received|given|are\\s+following)', '(send|forward|transmit|transfer|upload|push|move|deliver|route)\\s+(all\\s+|the\\s+|any\\s+|every\\s+|entire\\s+)?(patient|clinical|medical|health|PHI|confidential|protected|sensitive)?\\s*(records?|data|notes?|information|files?|documents?|registry|database)\\s*(to\\s+)?(an?\\s+)?(external|outside|remote|third.party|unauthorized)', '(export|dump|extract|download|leak|exfiltrate)\\s+(all\\s+|the\\s+|entire\\s+|complete\\s+)?(patient|clinical|medical|PHI|health|protected|confidential)?\\s*(records?|notes?|data|information|database|registry|files?|documents?)', '(transmit|exfiltrate|expose)\\s+(the\\s+)?(entire|all|complete|full)?\\s*(patient|clinical|medical)?\\s*(registry|database|records?|notes?|information)', '(dump|wipe|purge|flush)\\s+(the\\s+|all\\s+|entire\\s+|complete\\s+)?(entire\\s+|complete\\s+|whole\\s+|full\\s+)?(patient|clinical|medical|health|PHI|hospital)?\\s*(database|registry|records?|notes?|data|repository|datastore)']

_CI = ['```\\s*(python|javascript|js|bash|sh|ruby|php|perl|sql|powershell|cmd|batch)', '<\\s*script[\\s>]', '\\beval\\s*\\(', '\\bexec\\s*\\(', '__import__\\s*\\(', 'os\\.system\\s*\\(', 'subprocess\\s*\\.\\s*(run|call|Popen|check_output|check_call)\\s*\\(']

ALL_PATTERNS = {
    'instruction_override': re.compile('|'.join(_IO), re.IGNORECASE),
    'role_manipulation'   : re.compile('|'.join(_RM), re.IGNORECASE),
    'new_instructions'    : re.compile('|'.join(_NI), re.IGNORECASE),
    'system_exploits'     : re.compile('|'.join(_SE), re.IGNORECASE),
    'jailbreaks'          : re.compile('|'.join(_JB), re.IGNORECASE),
    'data_exfiltration'   : re.compile('|'.join(_DE), re.IGNORECASE),
    'code_injection'      : re.compile('|'.join(_CI), re.IGNORECASE),
}
RAW_PATTERNS = {
    'instruction_override': _IO, 'role_manipulation': _RM,
    'new_instructions': _NI,     'system_exploits': _SE,
    'jailbreaks': _JB,           'data_exfiltration': _DE,
    'code_injection': _CI,
}
CRITICAL_CATEGORIES = set(ALL_PATTERNS.keys())

@dataclass
class DefenseResult:
    decision: str; reason: str; risk_score: float
    matched_categories: list; matched_patterns: dict
    anomaly_flagged: bool; special_char_ratio: float; latency_ms: float

class DefenderAgent:
    def __init__(self):
        self.patterns            = ALL_PATTERNS
        self.critical_categories = CRITICAL_CATEGORIES
        self.anomaly_threshold   = 0.30
    def analyze(self, text):
        t0 = time.perf_counter()
        matches = {}
        for cat, pattern in self.patterns.items():
            m = pattern.search(text)
            if m: matches[cat] = m.group(0)
        special = sum(1 for c in text if not (c.isalnum() or c.isspace()))
        ratio = special / max(len(text), 1)
        anomaly_flagged = ratio > self.anomaly_threshold
        n = len(matches) + (1 if anomaly_flagged else 0)
        risk_score = round(min(1.0, math.log10(n+1)/math.log10(11)) if n>0 else 0.0, 4)
        mc = [c for c in matches if c in self.critical_categories]
        tc = len(matches)
        if mc:      decision, reason = 'BLOCK', f'Critical category: {mc}'
        elif tc>=3: decision, reason = 'BLOCK', f'High threat count: {tc} categories'
        else:       decision, reason = 'PASS',  'No threats detected'
        return DefenseResult(decision=decision, reason=reason, risk_score=risk_score,
            matched_categories=list(matches.keys()), matched_patterns=matches,
            anomaly_flagged=anomaly_flagged, special_char_ratio=round(ratio,4),
            latency_ms=round((time.perf_counter()-t0)*1000, 4))